### ISSUE TITLE
[Init] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Memo#1]
## Todo
- [x] .gitignore 추가 (프로젝트 내/외부)
- [x] 프로젝트 폴더링
- [x] Base/Extension 파일 추가
- [x] SPM 추가
- [ ] 폰트 파일 추가 및 적용
- [x] 컬러 에셋 추가 
- [x] Dark/Light 모드 설정 (Appearance)
