### ISSUE TITLE
[Feat] 메모 작성/수정 공통사항 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Memo#18]
## Todo
**공통사항**
- [x] 완료 버튼, 편집 상태 끝, back button, back gesture로 이전 화면으로 되돌아갈 경우 메모 저장
- [x] 어떤 텍스트도 입력하지 않으면 메모 삭제 (삭제 여부 확인하지 않음)
- [x] 리턴키 누르기 전까지 제목 / 누른 후 내용으로 저장 -> 텍스트뷰에 작성한 텍스트가 두 개의 컬럼으로 나눠서 저장 
- [x] 우측 상단 공유하기 버튼 누르면 메모 텍스트 UIActivityViewController로 공유
