### ISSUE TITLE
[UI] 최초진입 팝업창 UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Memo#2]
## Todo
- [x] 앱 최초 진입 팝업창 UI 구현
- [ ] 최초 진입 분기처리 
- [x] 최초 진입 -> 메인 화면 전환 연결
