### ISSUE TITLE
[Fix] 오류 수정 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Memo#21]
## Todo
**메모 리스트**
- [x] 메모 리스트 : 고정/미고정 Leading Swipe Action 갱신 오류 
- [ ] 메모 리스트 <-> 작성/수정하기 LargeTitle UI 오류

**메모 작성하기**
- [x] TitleTextView, ContentTextView 배경색 수정
- [x] TitleTextView, ContentTextView Responder 변화 

**메모 작성하기 -> 메모 리스트 화면전환**
- [x] 제목이 없을 경우, 삭제 / 내용만 없다면 추가 또는 업데이트
- [x] Back Gesture도 동일하게 적용 

**검색**
- [ ] 실시간 검색할 때 데이터 필터 + UI 변화
- [ ] 검색 취소 후 데이터 fetch 
- [ ] 검색 취소 후 UI 갱신 
- [ ] 검색 > cell 선택 > 이전 화면 플로우에서 발생하는 오류 수정
