### ISSUE TITLE
[Feat] 검색 화면 고정/삭제 기능 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Memo#22]
## Todo
- [x] 검색화면에서 leading swipe 할 때 고정
- [x] 검색화면에서 trailing swipe 할 때 삭제 
- [x] 고정 상태에 따른 UI/액션 분기처리
