### ISSUE TITLE
[Feat] Realm List 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Memo#28]
## Todo

- [x] 메모 폴더 테이블 구조 추가 
- [x] 렘 리스트 구현 
- [x] 앱 처음 실행 시 폴더 생성
- [x] 메모 추가시마다 폴더에 들어갈 수 있도록 구현
