### ISSUE TITLE
[Chore] 코드 및 파일 정리 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Memo#32]
## Todo

- [ ] 필요 없는 코드 정리
- [ ] 필요 없는 파일 삭제
- [ ] 기타 빌드 버전, 앱 이름 등 관리 및 수정
