### ISSUE TITLE
[Feat] Realm Database 적용

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Memo#5]
## Todo
- [x] SPM 파일 추가 
- [x] Realm Base 파일 추가 (Realm Model)
- [x] Realm에 Repository Pattern 적용
